name: CI Pipeline

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v4
        with:
          python-version: "3.13.1"

      - name: Install Python Dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest pytest-cov flask-testing

      - name: Run Python tests
        run: pytest --cov=app

      - name: Run Pylint
        run: pylint --fail-under=5 .

      #- name: Node.js Setup
      #  uses: actions/setup-node@v3
      #  with:
      #    node-version: "22.14.0"

      #- name: Install JS Dependencies
      #  run: npm install

      #- name: Run JavaScript tests
      #  run: npx jest

      #- name: Run Cypress tests
      #  run: npx cypress run
      
      #- name: Run ESLint
      #  run: npx eslint static/js/